# Generated by Django 4.0.4 on 2022-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', max_length=60, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.CharField(default='', max_length=100, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.CharField(default='', max_length=100, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=10, verbose_name='phone'),
        ),
    ]
