# Generated by Django 4.0.4 on 2022-05-07 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default='M', max_length=1)),
                ('isCriminal', models.BooleanField(default=False)),
                ('isTracked', models.BooleanField(default=False)),
                ('isFound', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=300)),
                ('applicant_email', models.EmailField(default='', max_length=60)),
                ('applicant_police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_tracking', models.DateTimeField(default=datetime.datetime(2022, 5, 7, 20, 9, 39, 498209, tzinfo=utc))),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
                ('missing_person', models.ManyToManyField(to='missing_people.missingperson')),
            ],
        ),
    ]
