# Generated by Django 4.0.4 on 2022-05-07 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 21, 0, 45, 803022, tzinfo=utc)),
        ),
    ]
