# Generated by Django 4.0.4 on 2022-05-07 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0002_missingperson_latitude_missingperson_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackhistory',
            name='missing_person',
        ),
        migrations.AddField(
            model_name='trackhistory',
            name='missing_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='missing_people.missingperson'),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 21, 32, 56, 60691, tzinfo=utc)),
        ),
    ]
