# Generated by Django 4.0.4 on 2022-05-07 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0004_alter_trackhistory_missing_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackhistory',
            name='missing_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_people.missingperson'),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 21, 36, 34, 663112, tzinfo=utc)),
        ),
    ]
