# Generated by Django 4.0.4 on 2022-05-07 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0006_alter_trackhistory_time_of_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 3, 14, 26, 439978)),
        ),
    ]
