# Generated by Django 4.0.4 on 2022-05-10 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0007_alter_trackhistory_time_of_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 4, 44, 20, 374368)),
        ),
    ]
