# Generated by Django 4.0.4 on 2022-05-17 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0009_missingperson_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackhistory',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='trackhistory',
            name='longitude',
        ),
        migrations.AddField(
            model_name='trackhistory',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='missing_people'),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 11, 39, 47, 527313)),
        ),
    ]
