# Generated by Django 4.0.4 on 2022-05-21 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0011_missingperson_person_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='details',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='person_uuid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 19, 42, 11, 305707)),
        ),
    ]
