# Generated by Django 4.0.4 on 2022-05-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0012_alter_missingperson_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='time_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 21, 49, 20, 1825)),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='time_of_first_tracking',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='time_of_found',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 21, 49, 20, 3815)),
        ),
    ]
