# Generated by Django 4.0.4 on 2022-05-23 18:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0001_initial'),
        ('missing_people', '0013_missingperson_time_of_addition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackhistory',
            name='captured_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='camera.capturedimages'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 0, 0, 5, 664288)),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 0, 0, 5, 665288)),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 5, 24, 0, 0, 5, 666288))),
                ('seen', models.BooleanField(default=False)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
