# Generated by Django 4.0.4 on 2022-05-24 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0014_trackhistory_captured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 15, 27, 23, 318981)),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_first_tracking',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_found',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 15, 27, 23, 319981)),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 15, 27, 23, 318981)),
        ),
    ]
