# Generated by Django 4.0.4 on 2022-05-25 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0015_alter_missingperson_time_of_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 14, 28, 25, 593125)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 14, 28, 25, 594126)),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 14, 28, 25, 594126)),
        ),
    ]
