# Generated by Django 4.0.4 on 2022-05-25 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0017_remove_trackhistory_captured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 1, 33, 19, 486277)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 1, 33, 19, 487277)),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images'),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 1, 33, 19, 487277)),
        ),
    ]
