# Generated by Django 4.0.4 on 2022-05-26 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_people', '0018_alter_missingperson_time_of_addition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='time_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 16, 31, 28, 801957)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 16, 31, 28, 804957)),
        ),
        migrations.AlterField(
            model_name='trackhistory',
            name='time_of_tracking',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 16, 31, 28, 803957)),
        ),
    ]
