# Generated by Django 4.0.4 on 2022-05-21 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraRecord',
            fields=[
                ('channel_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.TextField(default='', max_length=1000)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapturedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='captured_images')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='camera.camerarecord')),
            ],
        ),
    ]
