# Generated by Django 4.0.4 on 2022-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimages',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='captured_images'),
        ),
    ]
