# Generated by Django 4.0.4 on 2022-05-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0002_alter_capturedimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedimages',
            name='camera',
        ),
        migrations.AddField(
            model_name='capturedimages',
            name='location',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='capturedimages',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
