# Generated by Django 4.0.4 on 2022-05-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_remove_capturedimages_camera_capturedimages_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImages',
        ),
    ]
